name: ecinema_watch_together
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  flutter_dotenv: ^5.1.0
  firebase_storage: ^11.2.7
  flutter_device_type: ^0.4.0
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  firebase_auth: ^4.10.0
  get_storage: ^2.1.1
  carousel_slider: ^4.2.1
  image: ^4.1.3
  path_provider: ^2.1.1
  flutter_native_splash: ^2.3.3
  country_flags: ^2.1.1
  country_picker: ^2.0.21
  flutter_multi_formatter: ^2.11.12
  firebase_app_check: ^0.2.0+1
  cloud_functions: ^4.4.1
  localization: ^2.1.0
  intl: ^0.18.0
  encrypt: ^5.0.3
  crypto: ^3.0.3
  firebase_remote_config: ^4.3.1
  loading_animation_widget: ^1.2.0+4
  photo_gallery: ^2.1.1
  permission_handler: ^11.0.1
  transparent_image: ^2.0.1
  video_player: ^2.8.1
  flutter_image_compress: ^2.1.0
  image_cropper: ^5.0.0
  dotted_border: ^2.1.0
  appinio_video_player: ^1.2.2
  firebase_database: ^10.3.3
  video_compress:
    git:
      url: https://github.com/SpectoraSoftware/VideoCompress
      ref: caf41183e84adebd6ef5c8fba547937daf556a65 # Or master?
  video_thumbnail: ^0.5.3
  sticky_headers: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/avatars/
    - .env.production
    - .env.development

  fonts:
  - family: Poppins
    fonts: 
      - asset: assets/fonts/poppins/Poppins-100.ttf
        weight: 100
      - asset: assets/fonts/poppins/Poppins-200.ttf
        weight: 200
      - asset: assets/fonts/poppins/Poppins-300.ttf
        weight: 300
      - asset: assets/fonts/poppins/Poppins-400.ttf
        weight: 400
      - asset: assets/fonts/poppins/Poppins-500.ttf
        weight: 500
      - asset: assets/fonts/poppins/Poppins-600.ttf
        weight: 600
      - asset: assets/fonts/poppins/Poppins-700.ttf
        weight: 700
      - asset: assets/fonts/poppins/Poppins-800.ttf
        weight: 800
      - asset: assets/fonts/poppins/Poppins-900.ttf
        weight: 900

  - family: Roboto
    fonts: 
      - asset: assets/fonts/roboto/Roboto-100.ttf
        weight: 100
      - asset: assets/fonts/roboto/Roboto-200.ttf
        weight: 200
      - asset: assets/fonts/roboto/Roboto-400.ttf
        weight: 400
      - asset: assets/fonts/roboto/Roboto-500.ttf
        weight: 500
      - asset: assets/fonts/roboto/Roboto-600.ttf
        weight: 600
      - asset: assets/fonts/roboto/Roboto-700.ttf
        weight: 700

  - family: Barlow
    fonts: 
      - asset: assets/fonts/barlow/barlow_condensed_400.ttf
        weight: 400
      - asset: assets/fonts/barlow/barlow_condensed_700.ttf
        weight: 700
    
  - family: Climate
    fonts:
      - asset: assets/fonts/climate/Climate-400.ttf
        weight: 400

flutter_native_splash:
  android: true
  ios: true
  web: false
  fullscreen: true
  
  color: "#181818"
  image: "assets/images/ic_ecinema-logo-text2.png"